### ISSUE TITLE
Add permission check for api.ReloadUHash

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/go-pttbbs#192]
# Provide the github link(s) of the file#line (請提供 github 關於 code 的 link)

https://github.com/Ptt-official-app/go-pttbbs/blob/main/api/reload_uhash.go#L17

# What would you like to discuss (你想要討論什麼呢？～)

add permission check for api.ReloadUHash

**Comment by chhsiao1981** [comment]
permission check should be in bbs/

https://github.com/Ptt-official-app/go-pttbbs/blob/main/bbs/reload_uhash.go#L6

api.ReloadUHash needs to provide userID to bbs.

**Comment by tingyuchang** [comment]
in bbs, userID should be SYSOP, otherwise func will return ?

**Comment by chhsiao1981** [comment]
hi @tingyuchang 

Thanks for willing to help the issue～

api.ReloadUHash is actively reloading the user-hash
and should be limited with users with SYSOP or some similar permission～
otherwise we should return api.ErrInvalidUser.

we can use user.UserLevel.HasPerm(ptttype.PERM_SYSOP) for now
to check whether the user is valid.

we should check with ptt SYSOPs and meet their policy in the future.

https://github.com/Ptt-official-app/go-pttbbs/blob/main/ptttype/perm.go

**Comment by tingyuchang** [comment]
a small question:  `Userlevel:    536871943,`  in test case SYSOP used to  be set this value，but `PERM(536871943)&PERM_SYSOP` should be 0?  (65535 is good)

**Comment by chhsiao1981** [comment]
https://github.com/Ptt-official-app/go-pttbbs/blob/main/ptt/passwd.go#L23

這是 pttbbs 那裡的 feature～

每次做 api access 會用 InitCurrentUser 拿到現在的 user 的樣子.
然後 InitCurrentUser 裡會把 SYSOP 上 perm～

testcase 裡的 SYSOP 是根據 .PASSWDS 裡的設定而來的～

某種程度上反應真實情形 (.PASSWDS 裡的 SYSOP 的 perm 沒有站長權限 XD)

**Comment by tingyuchang** [comment]
ok 我懂了..... 那我 testcase 就手動加上權限吧
