### ISSUE TITLE
Unit test 失敗

### ISSUE THREAD

**Issue by cftang0827** [Ptt-official-app/go-pttbbs#207]
**Describe the bug**
在 `main` branch 跑測試，無論在 CI or local machine 上面跑都會得到這個錯誤
```
coverage: 100.0% of statements
ok  	github.com/Ptt-official-app/go-pttbbs/types/ansi	(cached)	coverage: 100.0% of statements
?   	github.com/Ptt-official-app/go-pttbbs/types/proto	[no test files]
```

此外在 CI 上面跑測試也獲得一樣的錯誤 https://github.com/Ptt-official-app/go-pttbbs/pull/206

**To Reproduce**
Follow the step from README.md
```./script/test.sh```

**Expected behavior**
All green

**Screenshots**
<img width="1030" alt="截圖 2021-06-07 02 59 42" src="https://user-images.githubusercontent.com/11738455/120935195-91063380-c73c-11eb-9d36-a44f8ef66ed5.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.3（20D91）

**Comment by chhsiao1981** [comment]
#164

**Comment by cftang0827** [comment]
same with https://github.com/Ptt-official-app/go-pttbbs/issues/173
closed
