### ISSUE TITLE
註冊 / login 會同步更改上站次數/上站時間.

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/go-pttbbs#250]
**Is your feature request related to a problem? Please describe.**

https://github.com/Ptt-official-app/go-openbbsmiddleware/issues/248

**Describe the solution you'd like**

c-pttbbs 相關的是在 user_login 裡有一個 pwcuLoginSave

https://github.com/ptt/pttbbs/blob/master/mbbsd/mbbsd.c#L1177
https://github.com/ptt/pttbbs/blob/master/mbbsd/mbbsd.c#L1249

go-pttbbs 已經有 userLogin 的殼. 但是還沒有完整 implement userLogin 裡的部分.
這個 issue 先在相對應的 ptt/passwd.go implement 出 pwcuLoginSave

    func pwcuLoginSave(uid ptttype.UID, user *ptttype.UserecRaw, ip *ptttype.IPv4_t) (isFirstLoginOfDay bool, err error) {
    }

https://github.com/Ptt-official-app/go-pttbbs/blob/main/ptt/mbbsd.go#L30
https://github.com/Ptt-official-app/go-pttbbs/blob/main/ptt/mbbsd.go#L81

https://github.com/Ptt-official-app/go-pttbbs/blob/main/ptt/passwd.go

**Describe alternatives you've considered**

**Additional context**

https://github.com/Ptt-official-app/go-openbbsmiddleware/issues/248

**Comment by tingyuchang** [comment]
看完感覺是從 lastlogin 來判斷，是否要 newNumLoginDays +1 ，還有處理每天最多 +1 的邏輯，另外這邊應該也需要更新以下的兩個參數嗎？
user.LastLogin = types.NowTS()
user.LastSeen = types.NowTS()

**Comment by chhsiao1981** [comment]
@tingyuchang 

是的～
大致上是如你所說的～

不過細節上會是

nowTS := types.NowTS()

(處理 user. numlogindays)
user.LastLogin = nowTS
user.LastSeen = nowTS
(把 user 寫進 shm 裡)

你很可以先用 [WIP] 的方式弄個 PR～
然後我們很可以一起討論你改的過程～
(我會 PR 到你的 repo 裡幫忙做細節的修改～)

**Comment by chhsiao1981** [comment]
#251 resolves this issue~
