### ISSUE TITLE
Board detail api

### ISSUE THREAD

**Issue by cftang0827** [Ptt-official-app/go-pttbbs#37]
**Is your feature request related to a problem? Please describe.**
There's no implement of board detail for `GetBoardDetail` API yet. Therefore, we need to create a new one. 

**Describe the solution you'd like**
We probably need to implement these files
- bbs/board_detail.go
- bbs/board_detail_test.go
- bbs/get_board_detail.go
- bbs/get_board_detail_test.go
- api/get_board_detail.go
- api/get_board_detail_test.go

Also need to check is there any feature from pttbbs C code, and implement Golang version in `ptt` folder 
And finally, register `get_board_detail` api in main.go

**Comment by cftang0827** [comment]
Start working on this one!

**Comment by cftang0827** [comment]
[Notes]
- 單純的 GET/POST(PUT) boardheader -> 
https://github.com/ptt/pttbbs/blob/master/include/pttstruct.h#L169
https://github.com/Ptt-official-app/go-pttbbs/blob/main/ptttype/board_header_raw.go
- 可以參考 board-summary 的方式做～
(就是把 board-header-raw load 完以後. 把相對應的 user-state 確認好
 然後不需要 parseSummary. 直接回傳 board-header-raw 和 user-state)

**Comment by cftang0827** [comment]
[Notes] -> 如果錯誤請告知，以下為個人心得筆記，以讀取Board header為例
- 每個板的基本資訊會記錄在 `.BRD` binary file中，架構如下圖所示
```
       +------------------+                                 
 0x0001|Board header 1    |                                 
       |---               |                                 
       |Board name        |                                 
       |Board title       |                                 
       |...etc            |                                 
       |------------------|                                 
 0x0005|Board header 2    |                                 
       |.....             |                                 
       |.....             |                                 
       |.....             |                                 
       |                  |                                                                               
       |------------------|                                 
       |        -         |                                 
       |        -         |                                 
       |        -         |                                 
       |        -         |                                 
       +------------------+                                              
```
基本上每一個板都會有屬於自己的一段位置
- 不過架構上並不會每次查詢board都去讀檔，這樣不符合經濟效益，所以系統在一段時間(或是剛launch process)的時候會把 `.BRD` load 進 share memory 中，也會有屬於自己的一段記憶體位置
- 目前讀取Board header的方式就是讀取 整塊cache記憶體資料內容 -> [連結](https://github.com/Ptt-official-app/go-pttbbs/blob/main/cache/cache_board.go#L24-L28)
- 目前 ptt 主機是採用monolithic的架構，也就是說所有的資料都是在一台主機上運行，所以本專案上線後，會與原有系統並存一段時間，並且共用share memory的部分來做資料的同步處理

**Comment by chhsiao1981** [comment]
大致上如 @cftang0827 所述

其中 shared-mem 是直接 follow c-pttbbs 既有的 shared-mem 的機制～
所以並不會佔用額外的 memory.

https://github.com/ptt/pttbbs/blob/master/common/bbs/cache.c#L431
https://github.com/ptt/pttbbs/blob/master/common/bbs/cache.c#L458

reload_bcache 是在每天 7:10am buildAnnounce 時發生～
https://github.com/ptt/pttbbs/blob/master/sample/crontab#L66

**Comment by chhsiao1981** [comment]
#259 resolves this issue.
